apiVersion: v1
kind: PersistentVolume
metadata:
  name: swagger-ui-pv
  namespace: swagger-ui
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Ensure this matches the PVC storageClassName
  hostPath:
    path: "/mnt/data/swagger-ui"
