apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swagger-ui-pvc
  namespace: swagger-ui
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: swagger-ui-pv
